### ISSUE TITLE
Add support for Dark Mode

### ISSUE THREAD

**Issue by j-martin** [j-martin/screenshot-chrome#1]
> Please add a dark theme. And make the default sync the extension theme with the system theme. More details: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

It should not be too hard to do.

**Comment by j-martin** [comment]
Resolved by 3ac8d308a3e16dca55c7b0492faf97ca935ae72a

**Comment by rakleed** [comment]
@j-martin could you please also make a dark background for the screenshot preview if I use a dark theme in the system/browser?

![image](https://github.com/user-attachments/assets/b44fdefe-2c3f-47ac-8936-ee57e4252b90)
