### ISSUE TITLE
Manifest V3 support

### ISSUE THREAD

**Issue by rakleed** [j-martin/screenshot-chrome#2]
The ability to install Manifest V2 extensions [will be completely unavailable in the coming months](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline). Please update your extension to [Manifest V3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3).

**Comment by j-martin** [comment]
Fixed by da202078f2a4effe4f5986b82f8f24773cc03720 and released in https://github.com/j-martin/screenshot-chrome/commit/77670c0043b9bdd5de29f056bef6e409d0821761

@rakleed you should be able to get the updated version from the Chrome store. 🙂

**Comment by rakleed** [comment]
Thanks!
